; Please do not edit this file! If this file is modified, results are unpredictable.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using the MEGA Prototyper.
[ MEGAinfo ]
ver                               = 7150910-64-bit MS Windows        
[ DataSettings ]
datatype                          = snNucleotide                     
containsCodingNuc                 = False                            
missingBaseSymbol                 = ?                                
identicalBaseSymbol               = .                                
gapSymbol                         = -                                
[ ProcessTypes ]
ppAlign                           = true                             
ppMuscle                          = true                             
[ AnalysisSettings ]
Gap Penalties                     = ====================             
Gap Open                          = -1.00                            
Gap Extend                        = 0.00                             
Memory/Iterations                 = ====================             
Max Memory in MB                  = 2048                             
Max Iterations                    = 16                               
Advanced Options                  = ====================             
Cluster Method (Iterations 1,2)   = UPGMA                            
Cluster Method (Other Iterations) = UPGMA                            
Min Diag Length (Lambda)          = 24                               
